services:
  client:
    image: client
    build:
      context: ./apps/client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  server:
    image: server 
    build:
      context: ./apps/server/
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
